"""Create table

Revision ID: 98f61960f5c6
Revises: 
Create Date: 2022-06-18 15:52:51.762536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f61960f5c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notice_board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('applicable_for', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('notice', sa.String(length=2550), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='nb_schema'
    )
    op.create_index(op.f('ix_nb_schema_notice_board_id'), 'notice_board', ['id'], unique=False, schema='nb_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nb_schema_notice_board_id'), table_name='notice_board', schema='nb_schema')
    op.drop_table('notice_board', schema='nb_schema')
    # ### end Alembic commands ###
